# -- Deploy Argo CD Applications within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/
applications: #[]
  - name: argocd-apps-clusters-test01
    namespace: argocd-init
    additionalLabels: {}
    additionalAnnotations: {}
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: test01
    source:
      #repoURL: https://github.com/YunchaeJung/k8scluster.git
     # repoURL: https://github.com/YunchaeJung/k8scluster
     # targetRevision: master
     # path: baremetal/clusters/test01/argocd-apps
     # directory:
     #   recurse: true
     # plugin:
     #   name: kustomize-build-with-helm
    # ArgoCD v2.6 or later
    sources:
     - repoURL: https://github.com/YunchaeJung/k8scluster.git
       path: baremetal/clusters/test01/argocd-apps-1.6.2
       targetRevision: master
       #plugin:
       #  name: kustomize-build-with-helm
    destination:
      server: https://192.168.116.131:6443
      namespace: argocd-init
    syncPolicy:
      automated:
        prune: false
        selfHeal: false
      syncOptions:
      - CreateNamespace=true
    revisionHistoryLimit: null
    ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
      - /spec/replicas

# -- Deploy Argo CD Projects within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/
projects: #[]
  - name: test01
    namespace: argocd-init
    additionalLabels: {}
    additionalAnnotations: {}
    permitOnlyProjectScopedClusters: false
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    description: test01 cluster
    sourceRepos:
    - 'https://github.com/YunchaeJung/k8scluster.git'
    destinations:
    - namespace: '*'
      server: https://192.168.116.131:6443
    clusterResourceWhitelist: #[]
      - group: '*'
        kind: '*'

# -- Deploy Argo CD ApplicationSets within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/
applicationsets: []
# - name: guestbook
#   namespace: argocd
#   additionalLabels: {}
#   additionalAnnotations: {}
#   # See PR #10026 (ArgoCD v2.5 or later)
#   # goTemplate: false
#   generators:
#   - git:
#       repoURL: https://github.com/argoproj/argocd-example-apps.git
#       revision: HEAD
#       directories:
#       - path: guestbook
#       - path: kustomize-*
#   # Ref https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#allow-temporarily-toggling-auto-sync
#   ignoreApplicationDifferences:
#   - jsonPointers:
#     - /spec/syncPolicy
#   # Progressive Syncs is an experimental feature and it must be explicitly enabled
#   # Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/#enabling-progressive-syncs
#   strategy:
#     type: RollingSync
#     rollingSync:
#       steps:
#       - matchExpressions:
#         - key: project
#           operator: In
#           values:
#           - guestbook
#       - matchExpressions:
#         - key: project
#           operator: In
#           values:
#           - kustomize-foo
#           - kustomize-bar
#   template:
#     metadata:
#       name: '{{path.basename}}'
#       labels:
#         project: '{{path.basename}}'
#       annotations: {}
#     spec:
#       project: default
#       source:
#         repoURL: https://github.com/argoproj/argocd-example-apps.git
#         targetRevision: HEAD
#         path: '{{path}}'
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: default
#       syncPolicy:
#         automated:
#           prune: false
#           selfHeal: false
#       ignoreDifferences:
#       - group: apps
#         kind: Deployment
#         jsonPointers:
#         - /spec/replicas
#       info:
#       - name: url
#         value: https://argoproj.github.io/
#   syncPolicy:
#     # Set Application finalizer
#     preserveResourcesOnDeletion: false
#   # Templating is only available on string type
#   templatePatch: |
#     spec:
#       source:
#         helm:
#           valueFiles:
#           {{- range $valueFile := .valueFiles }}
#             - {{ $valueFile }}
#           {{- end }}
#     {{- if .autoSync }}
#       syncPolicy:
#         automated:
#           prune: {{ .prune }}
#     {{- end }}

# --  Deploy Argo CD Applications/ApplicationSets/Projects within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/
itemTemplates: []
# - items:
#     - name: my-appset
#       generators: &generators
#         - list:
#             elements:
#               - cluster: engineering-dev
#                 url: https://1.2.3.4
#               - cluster: engineering-prod
#                 url: https://2.4.6.8
#               - cluster: finance-preprod
#                 url: https://9.8.7.6
#   template:
#     apiVersion: argoproj.io/v1alpha1
#     kind: ApplicationSet
#     metadata:
#       name: "{{ .name }}"
#     spec:
#       generators: *generators
#       template:
#         metadata:
#           name: "{{`{{cluster}}`}}-guestbook"
#         spec:
#           project: my-project
#           source:
#             repoURL: https://github.com/infra-team/cluster-deployments.git
#             targetRevision: HEAD
#             path: guestbook/{{`{{cluster}}`}}
#           destination:
#             server: "{{`{{cluster}}`}}"
#             namespace: guestbook
# - items:
#     - name: my-appset
#       generators:
#         - list:
#             elements:
#               - cluster: engineering-dev
#                 url: https://1.2.3.4
#               - cluster: engineering-prod
#                 url: https://2.4.6.8
#               - cluster: finance-preprod
#                 url: https://9.8.7.6
#   template: |-
#     apiVersion: argoproj.io/v1alpha1
#     kind: ApplicationSet
#     metadata:
#       name: {{ .name }}
#     spec:
#       generators: {{ toYaml .generators | nindent 4 }}
#       template:
#         metadata:
#           name: '{{`{{cluster}}`}}-guestbook'
#         spec:
#           project: my-project
#           source:
#             repoURL: https://github.com/infra-team/cluster-deployments.git
#             targetRevision: HEAD
#             path: guestbook/{{`{{cluster}}`}}
#           destination:
#             server: '{{`{{cluster}}`}}'
#             namespace: guestbook

# -- DEPRECATED - Please refer [Deprecation Notice](https://github.com/argoproj-labs/argocd-extensions?tab=readme-ov-file#deprecation-notice) for more info.
# @default -- `[]` (See [values.yaml])
## This function in tech preview stage, do expect unstability or breaking changes in newer versions. Bump image.tag if necessary.
## Ref: https://github.com/argoproj-labs/argocd-extensions
extensions: []
  # - name: example
  #   namespace: argocd
  #   additionalLabels: {}
  #   additionalAnnotations: {}
  #   sources:
  #     - git:
  #         url: https://github.com/argoproj-labs/argocd-example-extension.git
  #     - web:
  #         url: https://github.com/argoproj-labs/argocd-example-extension/releases/download/v0.1.0/extension.tar
